from llmprobe.scoring.aggregator import ReliabilityReport
from llmprobe.reporting.report import get_report_path, ensure_report_dir


def save_markdown_report(
    report: ReliabilityReport,
    output_dir: str = "reports"
) -> str:
    """
    Save a ReliabilityReport as a human readable Markdown file.
    Returns the path to the saved file.
    """
    ensure_report_dir(output_dir)
    path = get_report_path(output_dir, report.run_config.run_name, "md")

    lines = _build_markdown(report)

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Markdown report saved to: {path}")
    return path


def _build_markdown(report: ReliabilityReport) -> list[str]:
    """Build the markdown content as a list of lines."""
    lines = []

    # Header
    lines += [
        f"# LLMProbe Reliability Report",
        f"",
        f"**Model:** `{report.model_name}`  ",
        f"**Connector:** {report.connector_type}  ",
        f"**Run:** {report.run_config.run_name}  ",
        f"",
        f"---",
        f"",
    ]

    # Overall score
    rating = report.overall_rating["label"]
    score = report.overall_score
    lines += [
        f"## Overall Reliability Score",
        f"",
        f"# {score}/100 — {rating}",
        f"",
        _score_bar(score),
        f"",
        f"---",
        f"",
    ]

    # Dimension scores table
    lines += [
        f"## Dimension Scores",
        f"",
        f"| Dimension | Score | Rating | Failures |",
        f"|-----------|-------|--------|----------|",
    ]

    for name, data in report.dimension_scores.items():
        lines.append(
            f"| {name.capitalize()} "
            f"| {data['score']}/100 "
            f"| {data['rating']} "
            f"| {data['failure_count']} |"
        )

    lines += ["", "---", ""]

    # Failures section
    if report.all_failures:
        lines += [
            f"## Failure Examples",
            f"",
            f"Total failures found: **{len(report.all_failures)}**",
            f"",
        ]

        # Group failures by dimension
        by_dimension = {}
        for failure in report.all_failures:
            dim = failure.get("dimension", "unknown")
            if dim not in by_dimension:
                by_dimension[dim] = []
            by_dimension[dim].append(failure)

        for dim, failures in by_dimension.items():
            lines += [
                f"### {dim.capitalize()} Failures ({len(failures)})",
                f"",
            ]
            for i, failure in enumerate(failures[:5], 1):
                lines += _format_failure(failure, i)

    else:
        lines += [
            f"## Failure Examples",
            f"",
            f"No failures found. The model passed all tests.",
            f"",
        ]

    # Scoring weights used
    lines += [
        f"---",
        f"",
        f"## Scoring Weights Used",
        f"",
        f"| Dimension | Weight |",
        f"|-----------|--------|",
        f"| Hallucination | {report.run_config.weights.hallucination} |",
        f"| Consistency | {report.run_config.weights.consistency} |",
        f"| Adversarial | {report.run_config.weights.adversarial} |",
        f"| Bias | {report.run_config.weights.bias} |",
        f"",
        f"---",
        f"",
        f"*Generated by LLMProbe*",
    ]

    return lines


def _format_failure(failure: dict, index: int) -> list[str]:
    """Format a single failure example as markdown."""
    lines = [f"**Failure {index}**", ""]

    # Show relevant fields based on what's in the failure
    if "question" in failure:
        lines.append(f"- **Question:** {failure['question']}")
    if "prompt" in failure:
        lines.append(f"- **Prompt:** {failure['prompt'][:150]}...")
    if "prompt_a" in failure:
        lines.append(f"- **Prompt A:** {failure['prompt_a'][:100]}...")
        lines.append(f"- **Prompt B:** {failure['prompt_b'][:100]}...")
    if "expected_answer" in failure:
        lines.append(f"- **Expected:** {failure['expected_answer']}")
    if "model_response" in failure:
        lines.append(f"- **Got:** {failure['model_response'][:150]}")
    if "severity" in failure:
        lines.append(f"- **Severity:** {failure['severity']}")
    if "similarity" in failure:
        lines.append(f"- **Similarity:** {failure['similarity']}")
    if "flags" in failure:
        lines.append(f"- **Flags:** {', '.join(failure['flags'])}")
    if "classification" in failure:
        lines.append(f"- **Classification:** {failure['classification']}")

    lines.append("")
    return lines


def _score_bar(score: float, width: int = 20) -> str:
    """Generate a markdown-friendly score bar."""
    filled = int((score / 100) * width)
    bar = "█" * filled + "░" * (width - filled)
    return f"`{bar}` {score}%"